/**
*@Author Guillermo Jiménez De Sárraga
*/
export const crossWordCollection = [
    // ["I@AC@AL@AM@A@SCO@C@CL@CM@@N@B@D@T@@U@@E@AT@@AO@IN@M@AR@@I@BR@CN@BI@@I@FM@@GA@IR@ND@CD@O@COR@O@LI@NI@SN@@NSR@A@O@@O@@I@A@E@CS@@BA@B@O@ZNNE@T@CA@BE@@CU@I@GA@@RA@R@B@FLCF@TL@I@SI@K@R@O@@O@HO@@LA@CE@@@C@G@@M@I@B@@DBERKELIO@O@H@ES"],
    ["ALUMINIO@DC@@G@D@G@UT@C@B@B@SBI@E@O@RA@NN@S@H@O@BII@I@R@MN@OORO@I@O@@@@N@CO@@@@HL@C@@ERBIOINDIO@@A@@"],
    ["           ABERILIO  L         U         M         I         N         I         O                  "],
    // ["ACTINIO@A@AL@AS@@N@R@@C@L@AMT@A@S@AR@CU@@EA@N@B@R@A@MG@RT@TL@HG@R@I@BIO@I@A@O@S@ND@C@CM@S@N@E@I@LIA@O@@A@CN@O@@OT@NE@ZN@I@@BA@@NI@@U@@CD@A@BB@O@CF@CO@BR@EK@@C@R@@@F@I@@@BERKELIO@BORONH@@R@A@@P@@@G"],
    ["        @  @ @  @@  @ @@@@@ @ @       @   @  @  @  @ @  @ @  @ @  @ @      @     @ @@ @@@@  @       "],
    ["TECNECIO@BA@L@RU@@XE@O@@@@@B@R@RUTENIO@KCO@SR@NH@EA@N@BI@R@LL@E@IR@I@ICLORO@IODOI@N@@R@@@@OG@LANTANO"],
    ["         B @       E O  @  B R@RUTENIO@KCO  R  H EA@  B  R LL@  I  I ICLORO  O OI@       @O@@LANTANO"],
    ["EUROPIO@B@S@@@@@@@RBC@H@BARIO@A@A@I@@@MGN@FOSFORO@D@N@M@@@@TI@I@URANIOORO@TE@O@R@@@@O@@@@IZINC@CLORO"],
    ["A@        RE        GS        OT@TITANIONR @      @O R@TORIO N A       C D @ZINC I O@PLOMO O N@BARIO"],
    ["CALCIO@ORO@C    E@  @T N  IA  BI E@@NR  IN@ODISS@ SICDUNTEC MOLIBDENO@U@OMNDNIB T RIIIICR O OOOOOOE "],
    ["         B         E         R@RUTENIO@K         E         L         I         O         @          "],
    ["OXIGENO@@@R@@A@I@@@@G@@LUTECIOA@@I@R@U@@N@@ORO@R@@E@Z@@G@I@AS@I@@E@O@RS@NEON@@@GO@C@@OSMION@@@@@@@@N"],
    ["        C  A CADMIO  M   U  B NEON@B  A  R   N  L  I   I  T  CURIO  O  I        BORO          BOHRIO"],
    ["ANTIMONIOA    O  T CC P LI R TU L I  I IR A B  O NI T D  @ IO I ESTAÑO SN N  C  B O O C  CKR   TULIO"]
];

export const wordCollection = [
    ["ACTINIO", 7, "AC"],
    ["ALUMINIO", 8, "AL"],
    ["AMERICIO", 8, "AM"],
    ["ANTIMONIO", 9, "SB"],
    ["ARGON", 5, "AR"],
    ["ARSENICO", 8, "AS"],
    ["ASTATO", 6, "AT"],
    ["AZUFRE", 6, "S"],
    ["BARIO", 5, "BA"],
    ["BERILIO", 7, "BE"],
    ["BERKELIO", 8, "BK"],
    ["BISMUTO", 7, "BI"],
    ["BOHRIO", 6, "BH"],
    ["BORO", 4, "B"],
    ["BROMO", 5, "BR"],
    ["CADMIO", 6, "CD"],
    ["CALCIO", 6, "CA"],
    ["CALIFORNIO", 10, "CF"],
    ["CARBONO", 7, "C"],
    ["CERIO", 5, "CE"],
    ["CESIO", 5, "CS"],
    ["CLORO", 5, "CL"],
    ["COBALTO", 7, "CO"],
    ["COBRE", 5, "CU"],
    ["COPERNICIO", 11, "CN"],
    ["CROMO", 5, "CR"],
    ["CURIO", 5, "CM"],
    ["DARMSTADIO", 10, "DS"],
    ["DISPROSIO", 9, "DY"],
    ["DUBNIO", 6, "DB"],
    ["EINSTENIO", 9, "ES"],
    ["ERBIO", 5, "ER"],
    ["ESCANDIO", 8, "SC"],
    ["ESTAÑO", 6, "SN"],
    ["ESTRONCIO", 9, "SR"],
    ["EUROPIO", 7, "EU"],
    ["FERMIO", 6, "FM"],
    ["FLEROVIO", 9, "FL"],
    ["FLUOR", 5, "F"],
    ["FOSFORO", 7, "P"],
    ["FRANCIO", 7, "FR"],
    ["GADOLINIO", 9, "GD"],
    ["GALIO", 5, "GA"],
    ["GERMANIO", 8, "GE"],
    ["HAFNIO", 6, "HF"],
    ["HASSIO", 6, "HS"],
    ["HELIO", 5, "HE"],
    ["HIDROGENO", 9, "H"],
    ["HIERRO", 6, "FE"],
    ["HOLMIO", 6, "HO"],
    ["INDIO", 5, "IN"],
    ["IODO", 4, "I"],
    ["IRIDIO", 6, "IR"],
    ["ITERBIO", 7, "YB"],
    ["ITRIO", 5, "Y"],
    ["KRYPTON", 7, "KR"],
    ["LANTANO", 7, "LA"],
    ["LAWRENCIO", 9, "LR"],
    ["LITIO", 5, "LI"],
    ["LIVERMORIO", 11, "LV"],
    ["LUTECIO", 7, "LU"],
    ["MAGNESIO", 8, "MG"],
    ["MANGANESO", 9, "MN"],
    ["MEITNERIO", 9, "MT"],
    ["MENDELEVIO", 10, "MD"],
    ["MERCURIO", 8, "HG"],
    ["MOLIBDENO", 9, "MO"],
    ["MOSCOVIO", 9, "MC"],
    ["NEODIMIO", 8, "ND"],
    ["NEON", 4, "NE"],
    ["NEPTUNIO", 8, "NP"],
    ["NIHONIO", 8, "NH"],
    ["NIOBIO", 6, "NB"],
    ["NIQUEL", 6, "NI"],
    ["NITROGENO", 9, "N"],
    ["NOBELIO", 7, "NO"],
    ["ORGANESON", 10, "OG"],
    ["ORO", 3, "AU"],
    ["OSMIO", 5, "OS"],
    ["OXIGENO", 7, "O"],
    ["PALADIO", 7, "PD"],
    ["PLATA", 5, "AG"],
    ["PLATINO", 7, "PT"],
    ["PLOMO", 5, "PB"],
    ["PLUTONIO", 8, "PU"],
    ["POLONIO", 7, "PO"],
    ["POTASIO", 7, "K"],
    ["PRASEODIMIO", 11, "PR"],
    ["PROMECIO", 8, "PM"],
    ["PROTACTINIO", 11, "PA"],
    ["RADIO", 5, "RA"],
    ["RADON", 5, "RN"],
    ["RENIO", 5, "RE"],
    ["RODIO", 5, "RH"],
    ["ROENTGENIO", 11, "RG"],
    ["RUBIDIO", 7, "RB"],
    ["RUTENIO", 7, "RU"],
    ["RUTHERFORDIO", 12, "RF"],
    ["SAMARIO", 7, "SM"],
    ["SEABORGIO", 9, "SG"],
    ["SELENIO", 7, "SE"],
    ["SILICE", 6, "SI"],
    ["SODIO", 5, "NA"],
    ["TALIO", 5, "TL"],
    ["TANTALIO", 8, "TA"],
    ["TECNECIO", 8, "TC"],
    ["TELURO", 6, "TE"],
    ["TENNESSINE", 10, "TS"],
    ["TERBIO", 6, "TB"],
    ["TITANIO", 7, "TI"],
    ["TORIO", 5, "TH"],
    ["TULIO", 5, "TM"],
    ["URANIO", 6, "U"],
    ["VANADIO", 7, "V"],
    ["WOLFRAMIO", 9, "W"],
    ["XENON", 5, "XE"],
    ["ZINC", 4, "ZN"],
    ["ZIRCONIO", 8, "ZR"]
  ];